choco feature enable --name="usePackageExitCodes"
choco feature enable --name="useRememberedArgumentsForUpgrades"
choco feature enable --name="stopOnFirstPackageFailure"
choco feature disable --name="logWithoutColor"
choco feature disable --name="showDownloadProgress"
choco config unset --name="proxy"
choco config unset --name="proxyUser"
choco config unset --name="proxyPassword"
choco config set --name="proxy" --value="pdxproxy.dmz.unicru.com:8080"
choco config set --name="proxyUser" --value="svc_proxy"
choco config set --name="proxyPassword" --value="P2ss4PROXY"
